# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Deuteri's Blog
site_url: https://hieuhdh.github.io/
site_author: Deuteri
site_description: >-
  Hello everyone, I’m Deuteri and all you guy can call me “Deu”. I’m a student

# Repository
repo_name: hieuhdh/hieuhdh.github.io
repo_url: https://github.com/hieuhdh/hieuhdh.github.io.git

# Copyright
copyright: Copyright &copy; 2022 Deuteri

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]
  #custom_dir: overrides
  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
  font:
    text: Fira Sans
    code: Fira Code
  favicon: assets/favicon.png
  icon:
    logo: logo
    tag:
      default: octicons/tag-16
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
      c++: fontawesome/brands/c++

# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        changelog/insiders.md: insiders/changelog.md
        conventions.md: philosophy.md
        reference/abbreviations.md: reference/tooltips.md
        reference/meta-tags.md: reference/index.md
        reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
        sponsorship.md: insiders/index.md
        upgrading.md: upgrade.md
  - minify:
      minify_html: true

  - tags:
      tags_file: tags/tags.md
  - mkdocs-video
  # - git-revision-date-localized:
  #     enabled: !ENV [ENABLED_GIT_REVISION_DATE, True]

# Customization
extra:
  consent:
    actions:
      - accept
      - manage
    cookies:
      analytics: Google Analytics 
      custom: Custom cookie
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target=_blank>feedback form</a>.
    provider: google
    # property: !ENV GOOGLE_ANALYTICS_KEY
    property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/ao.lncb/
    - icon: fontawesome/brands/github
      link: https://github.com/hieuhdh
    - icon: fontawesome/brands/linkedIn
      link: https://www.linkedin.com/in/hieuhdh/
extra_javascript:
  - javascripts/agree.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: hieuhdh
      repo: hieuhdh.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md

  - Blogs:
    - blog/index.md
    - Abstract Mathematics:
      - Abstract Algebra:
        - blog/abstract-mathematics/abstract-algebra/2020-10-15-modules.md
        - blog/abstract-mathematics/abstract-algebra/2021-07-06-boolean.md
    - CTF:
      - Cryptography:
        - blog/ctf/cryptography/2020-10-10-picoCTF-2019.md
        - blog/ctf/cryptography/2021-05-10-picoCTF-2021.md
    - Cryptography:
      - Cryptographic Algorithms:
        - Substitution Cipher:
          - Monoalphabetic Cipher:
            - blog/cryptography/cryptographic-algorithms/substitution-cipher/monoalphabetic-cipher/index.md
            - blog/cryptography/cryptographic-algorithms/substitution-cipher/monoalphabetic-cipher/2020-12-09-rotx.md
          - Polyalphabetic Cipher:
            - blog/cryptography/cryptographic-algorithms/substitution-cipher/polyalphabetic-cipher/index.md
        - Sysmetric Cryptosystems:
          - Updating
        - Public-key Cryptosystems:
          - blog/cryptography/cryptographic-algorithms/public-key-cryptosystems/2020-12-17-rsa.md
          - blog/cryptography/cryptographic-algorithms/public-key-cryptosystems/2021-05-11-elgamal.md
      - Some problems:
        - blog/cryptography/problems/2021-06-01-yao's-millionaire-problem.md
    - Computer Programming:
      - Object-oriented programming:
        - blog/cumputer-programming/oop/2021-03-01-01-oop-class.md
        - blog/cumputer-programming/oop/2021-03-01-02-oop-encapsulation.md
        - blog/cumputer-programming/oop/2021-03-01-03-oop-abstraction.md
        - blog/cumputer-programming/oop/2021-03-01-04-oop-inheritance.md
        - blog/cumputer-programming/oop/2021-03-01-05-oop-polymorphism.md
    - Malware:
      - None

  - Projects:
    - project/index.md
    - Năm 2021:
      - Tháng 6:
        - project/2021/06/food-inspection-program.md
        - project/2021/06/robotic-vacuum-cleaner.md
      - Tháng 7:
        - project/2021/07/attendance-management-system.md
      - Tháng 8:
        - project/2021/08/brute-force-insider-attack.md
      - Tháng 9:
          - project/2021/09/quadratic-equations.md
          - project/2021/09/multi-tasking-program.md
      - Tháng 12:
          - project/2021/12/go-chess.md
    - Năm 2022:
      - Tháng 6:
        - project/2022/chinese-search-support.md
  - Categories: tags/tags.md
# extra_css:
#   - stylesheets/extra.css